version: '3'
services:
  redis-server:
    container_name: 'my_redis_server'
    restart: on-failure
    image: 'redis'
  node-app:
    container_name: 'my_application_node'
    restart: always
    build: .
    ports:
      - "8081:8081"
      - "8080:8081"
      - "4001:8081"
    depends_on:
      - "redis-server"
