apiVersion: v1
kind: Service
metadata:
  name: prometheus-ip-service
  namespace: default
  # namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /metrics
      prometheus.io/port:   '9090'

spec:
  selector:
    app: prometheus-server
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
